# Generated by Django 5.0.6 on 2024-06-23 03:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='description',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(5, 'Description must be at least 5 characters long.')]),
        ),
        migrations.AlterField(
            model_name='issue',
            name='title',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(3, 'Title must be at least 3 characters long.')]),
        ),
    ]
