# Generated by Django 5.0.6 on 2024-06-14 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_alter_problem_category_alter_problem_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='problem',
            name='category',
            field=models.CharField(choices=[('arrays', 'Arrays'), ('linked_lists', 'Linked Lists'), ('sorting', 'Sorting'), ('searching', 'Searching'), ('trees', 'Trees'), ('graphs', 'Graphs'), ('dynamic_programming', 'Dynamic Programming'), ('recursion', 'Recursion'), ('backtracking', 'Backtracking'), ('bit_manipulation', 'Bit Manipulation'), ('greedy', 'Greedy'), ('math', 'Math'), ('geometry', 'Geometry'), ('combinatorics', 'Combinatorics'), ('probability', 'Probability'), ('game_theory', 'Game Theory'), ('puzzles', 'Puzzles'), ('miscellaneous', 'Miscellaneous')], default='miscellaneous', max_length=20),
        ),
        migrations.AlterField(
            model_name='problem',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=10),
        ),
    ]
