# Generated by Django 5.0.6 on 2024-06-27 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_problem_status_alter_problem_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='memory_limit',
            field=models.IntegerField(default=256),
        ),
        migrations.AddField(
            model_name='problem',
            name='restrictions',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='problem',
            name='time_limit',
            field=models.IntegerField(default=1),
        ),
    ]
