# Generated by Django 5.0.6 on 2024-06-13 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Homework',
        ),
    ]
