# Generated by Django 5.0.6 on 2024-06-15 00:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_delete_homework'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='tag',
            field=models.CharField(default='tst', max_length=3, validators=[django.core.validators.RegexValidator(message='Tag-ul poate conține doar litere și cifre.', regex='^[a-zA-Z0-9]*$')]),
            preserve_default=False,
        ),
    ]
