# Generated by Django 5.0.6 on 2024-06-13 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0003_delete_homework'),
        ('problems', '0003_alter_problem_category_alter_problem_difficulty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateTimeField()),
                ('class_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='classes.class')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='problems.problem')),
            ],
        ),
    ]
